# Generated by Django 5.0.14 on 2026-02-10 16:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The name of the category.', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='SEO-friendly URL component.', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The full name of the product.', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the product.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Retail price of the product.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('stock_quantity', models.IntegerField(default=0, help_text='Current available stock.', validators=[django.core.validators.MinValueValidator(0)])),
                ('image_url', models.URLField(blank=True, help_text='URL for the primary product image.', max_length=2000, null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Whether the product is currently purchasable.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='The primary category this product belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the user submitting the review.', max_length=255)),
                ('rating', models.IntegerField(help_text='Rating given to the product (1 to 5 stars).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='The text of the review.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='The product being reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('product', 'name')},
            },
        ),
    ]
